.TH "main.c" 3 "Sun Dec 9 2012" "Version v1.0" "WLLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'list\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest1PushBackAndPushFront\fP ()"
.br
.ti -1c
.RI "void \fBtest2ListFromString\fP ()"
.br
.ti -1c
.RI "void \fBtest3MergeLists\fP ()"
.br
.ti -1c
.RI "void \fBtest4FlattenList\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 81 of file main\&.c\&.
.SS "void test1PushBackAndPushFront ()"

.PP
Definition at line 5 of file main\&.c\&.
.SS "void test2ListFromString ()"

.PP
Definition at line 22 of file main\&.c\&.
.SS "void test3MergeLists ()"

.PP
Definition at line 37 of file main\&.c\&.
.SS "void test4FlattenList ()"

.PP
Definition at line 63 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WLLC from the source code\&.
