.TH "wllc" 3 "Sun Dec 9 2012" "Version v1.0" "WLLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wllc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "struct \fBwllc\fP * \fBsub\fP"
.br
.ti -1c
.RI "struct \fBwllc\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file list\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBwllc\fP* next"
pointer to next list node 
.PP
Definition at line 24 of file list\&.h\&.
.SS "struct \fBwllc\fP* sub"
pointer to sublist 
.PP
Definition at line 22 of file list\&.h\&.
.SS "int type"
defines type of node 
.PP
Definition at line 18 of file list\&.h\&.
.SS "int val"
value stored in node 
.PP
Definition at line 20 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WLLC from the source code\&.
